version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: mongo_scraper
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/productos

  scraper:
    build: ./scraper
    container_name: scraper_bot
    depends_on:
      - backend
  
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: