name: Ejecutar Scrapers

on:
  schedule:
    - cron: '0 3 * * *' # Ejecutar diariamente a las 3:00 AM UTC

  workflow_dispatch:

jobs:
  run-scrapers:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r scraper/requirements.txt

      - name: Ejecutar scrapers
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python scraper/run_all.py
